services:
  web:
    ports:
      - "8787:8787"
    image: "portkeyai/gateway:1.8.7"
    restart: always

  wiremock:
    image: "wiremock/wiremock:latest"
    container_name: wiremock
    ports:
      - 8081:8080
    volumes:
      - ./docker/wiremock/mappings:/home/wiremock/mappings
    entrypoint: ["/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose"]  